Bump org.jetbrains.kotlinx:kotlinx-serialization-json from 1.7.2 to 1.7.3 in the kotlin group (#120)
Bumps the kotlin group with 1 update:
[org.jetbrains.kotlinx:kotlinx-serialization-json](https://github.com/Kotlin/kotlinx.serialization).

Updates `org.jetbrains.kotlinx:kotlinx-serialization-json` from 1.7.2 to
1.7.3
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/Kotlin/kotlinx.serialization/releases">org.jetbrains.kotlinx:kotlinx-serialization-json's
releases</a>.</em></p>
<blockquote>
<h2>1.7.3</h2>
<p>This release aims to fix important issues that were discovered in the
1.7.2 release,
including the inability to sync certain projects into Android
Studio/IntelliJ IDEA and exceptions from custom Uuid serializers.</p>
<p>It uses Kotlin 2.0.20 by default.</p>
<ul>
<li>Use explicit kotlin-stdlib and kotlin-test versions from version
catalog (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2818">#2818</a>)</li>
<li>Drop usage of deprecated Any?.freeze() in K/N target (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2819">#2819</a>)</li>
<li>Check against serialName instead of simpleClassName (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2802">#2802</a>)</li>
<li>Ignore NoClassDefFoundError when initializing builtins map for
serializer() function (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2803">#2803</a>)</li>
<li>Clarify example for SerializationException (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2806">#2806</a>)</li>
</ul>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/Kotlin/kotlinx.serialization/blob/master/CHANGELOG.md">org.jetbrains.kotlinx:kotlinx-serialization-json's
changelog</a>.</em></p>
<blockquote>
<h1>1.7.3 / 2024-09-19</h1>
<p>This release aims to fix important issues that were discovered in the
1.7.2 release,
including the inability to sync certain projects into Android
Studio/IntelliJ IDEA and exceptions from custom Uuid serializers.</p>
<p>It uses Kotlin 2.0.20 by default.</p>
<ul>
<li>Use explicit kotlin-stdlib and kotlin-test versions from version
catalog (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2818">#2818</a>)</li>
<li>Drop usage of deprecated Any?.freeze() in K/N target (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2819">#2819</a>)</li>
<li>Check against serialName instead of simpleClassName (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2802">#2802</a>)</li>
<li>Ignore NoClassDefFoundError when initializing builtins map for
serializer() function (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2803">#2803</a>)</li>
<li>Clarify example for SerializationException (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2806">#2806</a>)</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/Kotlin/kotlinx.serialization/commit/d4d066d72a9f92f06c640be5a36a22f75d0d7659"><code>d4d066d</code></a>
Prepare 1.7.3 release (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2821">#2821</a>)</li>
<li><a
href="https://github.com/Kotlin/kotlinx.serialization/commit/21311a61b3cb26ddbc30a3587588bacc6c2fb309"><code>21311a6</code></a>
Clarify example for SerializationException (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2806">#2806</a>)</li>
<li><a
href="https://github.com/Kotlin/kotlinx.serialization/commit/2f1dbdb1c4911ff506ce41d410b05ada4e6c00b7"><code>2f1dbdb</code></a>
Use explicit kotlin-stdlib and kotlin-test versions from version catalog
(<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2818">#2818</a>)</li>
<li><a
href="https://github.com/Kotlin/kotlinx.serialization/commit/595bcbdbc69a08f46072d2e7e0c09519a65aaa86"><code>595bcbd</code></a>
Drop usage of deprecated Any?.freeze() in K/N target (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2819">#2819</a>)</li>
<li><a
href="https://github.com/Kotlin/kotlinx.serialization/commit/d9753afd4ba011d33d39b02bb9dcf9d75a949632"><code>d9753af</code></a>
Check against serialName instead of simpleClassName (<a
href="https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2802">#2802</a>)</li>
<li><a
href="https://github.com/Kotlin/kotlinx.serialization/commit/0b015e13599a159cca198d5d5e633b90211e6f85"><code>0b015e1</code></a>
Ignore NoClassDefFoundError when initializing builtins map for
serializer() f...</li>
<li>See full diff in <a
href="https://github.com/Kotlin/kotlinx.serialization/compare/v1.7.2...v1.7.3">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=org.jetbrains.kotlinx:kotlinx-serialization-json&package-manager=gradle&previous-version=1.7.2&new-version=1.7.3)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore <dependency name> major version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's major version (unless you unignore this specific
dependency's major version or upgrade to it yourself)
- `@dependabot ignore <dependency name> minor version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's minor version (unless you unignore this specific
dependency's minor version or upgrade to it yourself)
- `@dependabot ignore <dependency name>` will close this group update PR
and stop Dependabot creating any more for the specific dependency
(unless you unignore this specific dependency or upgrade to it yourself)
- `@dependabot unignore <dependency name>` will remove all of the ignore
conditions of the specified dependency
- `@dependabot unignore <dependency name> <ignore condition>` will
remove the ignore condition of the specified dependency and ignore
conditions


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>